"""Run with: python -m instagram_tracker

Set IG_HTTPS=1 to run over TLS using the self-signed cert generated by
scripts/make-cert.sh. Default mode stays plain HTTP on port 8000 — HTTPS
is opt-in because plain mode is fine when accessing from the same Mac.
"""

import os
import socket
import sys
from pathlib import Path

import uvicorn

from .config import DEFAULT_HOST, DEFAULT_PORT


def lan_ip() -> str | None:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        return None


def main():
    port = DEFAULT_PORT
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            pass

    https_on = os.environ.get("IG_HTTPS", "").strip() not in ("", "0", "false", "False")
    repo_root = Path(__file__).resolve().parent.parent
    cert_path = Path(os.environ.get("IG_CERT", repo_root / "data" / "cert.pem"))
    key_path = Path(os.environ.get("IG_KEY",   repo_root / "data" / "key.pem"))
    scheme = "http"
    ssl_kwargs: dict = {}

    if https_on:
        if not cert_path.exists() or not key_path.exists():
            print(f"IG_HTTPS=1 set but cert/key missing:")
            print(f"  cert: {cert_path}  exists={cert_path.exists()}")
            print(f"  key:  {key_path}  exists={key_path.exists()}")
            print("Run ./scripts/make-cert.sh once to generate them, then retry.")
            sys.exit(1)
        scheme = "https"
        ssl_kwargs = {
            "ssl_certfile": str(cert_path),
            "ssl_keyfile": str(key_path),
        }
        # If the user didn't pick a port and IG_HTTPS is on, default to 8443
        # by convention so 8000 stays free for plain HTTP. Override via CLI.
        if port == DEFAULT_PORT and len(sys.argv) <= 1:
            port = 8443

    print()
    print("=" * 60)
    print("  Instagram Tracker" + ("  (HTTPS)" if https_on else ""))
    print("=" * 60)
    print(f"  Mac:    {scheme}://localhost:{port}")
    ip = lan_ip()
    if ip:
        print(f"  Phone:  {scheme}://{ip}:{port}    (same Wi-Fi)")
    if https_on:
        print(f"  Cert:   {cert_path}")
    print("=" * 60)
    print("  Stop with Ctrl-C")
    print()

    # Memory watchdog: long-running Python services don't return memory
    # back to the OS after GC, so cumulative-compute caches and
    # transient working sets pile up indefinitely. After ~5 hours of
    # bot-driven traffic the live process was at 3.2 GB and /api/home
    # cold-cache had blown past 3 minutes. Periodically check RSS, and
    # if over the threshold re-exec ourselves in place so the OS
    # reclaims memory while the listener stays up. Default 1500 MB;
    # IG_MEMORY_LIMIT_MB=0 disables the watchdog entirely.
    import subprocess as _subprocess
    import threading as _threading
    import time as _time
    _mem_limit_mb = int(os.environ.get("IG_MEMORY_LIMIT_MB", "1500"))
    _mem_check_interval_s = 180  # 3 min — re-exec is in-process and
    # near-invisible, so we can poll often and catch bloat from a
    # single heavy compute (cumulative diff peaks at ~1.8 GB) before
    # it sits in RSS for 10 min.
    if _mem_limit_mb > 0:
        def _memory_watchdog():
            pid = os.getpid()
            while True:
                _time.sleep(_mem_check_interval_s)
                try:
                    r = _subprocess.run(
                        ["ps", "-o", "rss=", "-p", str(pid)],
                        capture_output=True, text=True, timeout=5,
                    )
                    rss_mb = int(r.stdout.strip()) / 1024  # ps reports KB
                    if rss_mb > _mem_limit_mb:
                        print(
                            f"[memory-watchdog] RSS {rss_mb:.0f} MB > "
                            f"{_mem_limit_mb} MB threshold — re-execing "
                            f"to reclaim memory",
                            flush=True,
                        )
                        os.execv(sys.executable,
                                 [sys.executable, "-m", "instagram_tracker"]
                                 + sys.argv[1:])
                except Exception as e:
                    print(f"[memory-watchdog] check failed: {e}", flush=True)
        _threading.Thread(target=_memory_watchdog, daemon=True).start()
        print(f"  Memory watchdog: limit {_mem_limit_mb} MB, "
              f"check every {_mem_check_interval_s // 60} min")
        print()

    uvicorn.run(
        "instagram_tracker.server:app",
        host=DEFAULT_HOST,
        port=port,
        log_level="info",
        # Auto-reload opt-in via IG_RELOAD=1. Default OFF because under
        # launchd / any long-lived daemon context, the reload watcher
        # was observed pegging multiple cores indefinitely (PID 344
        # incident: 380% CPU for 54 min). Use launchctl kickstart to
        # pick up code changes manually.
        reload=os.environ.get("IG_RELOAD", "").strip() not in ("", "0", "false", "False"),
        reload_dirs=(["instagram_tracker"]
                     if os.environ.get("IG_RELOAD", "").strip() not in ("", "0", "false", "False")
                     else None),
        **ssl_kwargs,
    )


if __name__ == "__main__":
    main()
